#!/usr/bin/env python3

import argparse
import sys

if __name__ == "__main__":
	parser = argparse.ArgumentParser(description='Sliding window mapper for many-cores')
	parser.add_argument('size', type=int, help="many-core dimension in either X or Y")
	parser.add_argument('page_number', type=int, help="many-core page number for each PE")
	parser.add_argument('test_name', help="output name for this program session")

	parser.add_argument('--w', type=int, help="sliding window starting size", default=3)
	parser.add_argument('--stride', type=int, help="sliding window stride", default=2)

	args = parser.parse_args()

	sys.path.append("./modules")
	from mapper import Mapper

	mapper = Mapper(args.page_number, args.w, args.stride, args.size, args.test_name)

	mapper.interactive()
